# use optimized configuration for production environment
services:
  api:
    image: ghcr.io/michael-coding06/livestream-backend:staging
    command: ./producer  # Chạy thẳng file binary đã nén
    ports:
      - "8087:8087"
    restart: always
    environment:
      KAFKA_BROKER: kafka1:9092,kafka2:9093
      MYSQL_DSN: root:root@tcp(mysql:3306)/streampulse
      REDIS_ADDR: redis:6379

  consumer:
    image: ghcr.io/michael-coding06/livestream-backend:staging
    command: ./consumer  # Chạy thẳng file binary
    restart: always
    environment:
      KAFKA_BROKER: kafka1:9092,kafka2:9093
      MYSQL_DSN: root:root@tcp(mysql:3306)/streampulse
      REDIS_ADDR: redis:6379