CREATE TABLE IF NOT EXISTS rooms (
  room_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  host VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS room_stats (
  room_id VARCHAR(64) PRIMARY KEY,
  comments BIGINT DEFAULT 0,
  likes BIGINT DEFAULT 0,
  gifts BIGINT DEFAULT 0,
  joins BIGINT DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  room_id VARCHAR(64),
  user_id VARCHAR(64),
  type VARCHAR(32),
  gift_value INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
